X-MID: $msgid_$callsign
To: $toaddr
Subject: $subject
X-Type: Email; Outmail
X-Status: Posted
X-Via: Sailmail
X-Date: 2014/02/19 05:18:26

Hi All!

Our location details as of $date @ $time are:

Name: $locname
Latitude: $loclat
Longitude: $loclon
Description: $locdesc

View in Google Maps: Name: https://maps.google.com.au/maps?q=$loclatdec,$loclondec&num=1&t=h&z=4 

This is an automated message, but feel free to respond!

Love
H&K

